In [1]:
print("Hello world!")

Hello world!


In [15]:
from datetime import datetime, date, time

dt = datetime(2011, 10, 29, 20, 30, 21)
dt.date()

datetime.date(2011, 10, 29)

In [16]:
dt.time()

datetime.time(20, 30, 21)

In [18]:
dt.strftime('%m %d %Y')

'10 29 2011'

In [19]:
dt.strptime('10 29 2011', '%m %d %Y')

datetime.datetime(2011, 10, 29, 0, 0)

In [43]:
a = list(range(1,10,2))
a.extend([12,14])
print(a)
a.append([12,14])
print(a)

[1, 3, 5, 7, 9, 12, 14]
[1, 3, 5, 7, 9, 12, 14, [12, 14]]


In [35]:
#enumerate
some_list = ['foo', 'bar', 'baz']
mapping = {}
for i, v in enumerate(some_list):
    mapping[v] = i
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

In [50]:
#zip
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
for i, v in zip(seq1, seq2):
    print(i,v)
print(list(zip(seq1,seq2)))

pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'),('Schilling', 'Curt')]
first_name, last_name = zip(*pitchers)
first_name

foo one
bar two
baz three
[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]


('Nolan', 'Roger', 'Schilling')

In [51]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [54]:
d1 = {'a' : 'some value', 'b' : [1, 2, 3, 4]}
d1.pop('a')
d1

{'b': [1, 2, 3, 4]}

In [57]:
d1['a'] = 'wei'
d1.update({'b' : 'foo', 'c' : 12})
d1

{'b': 'foo', 'c': 12, 'a': 'wei'}

In [60]:
mapping = dict(zip(range(5), reversed(range(5))))
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

# Numpy

In [17]:
import numpy as np

In [63]:
data = np.random.randn(2,3)
data

array([[ 0.40482422, -0.23300739, -1.57174642],
       [-0.12059469,  0.60684113, -1.16633716]])

In [64]:
data.shape

(2, 3)

In [66]:
data.ndim

2

In [65]:
data.dtype

dtype('float64')

In [67]:
np.zeros(3)

array([0., 0., 0.])

In [68]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.r_[data,np.zeros_like(data)]

array([[ 0.40482422, -0.23300739, -1.57174642],
       [-0.12059469,  0.60684113, -1.16633716],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [72]:
np.c_[data, np.ones_like(data)]

array([[ 0.40482422, -0.23300739, -1.57174642,  1.        ,  1.        ,
         1.        ],
       [-0.12059469,  0.60684113, -1.16633716,  1.        ,  1.        ,
         1.        ]])

In [73]:
arr = np.arange(10)
arr[3]

3

In [83]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [90]:
#对切片表达式的赋值操作会被扩散到整个选区
arr_slice[1] = 1234
arr

array([   0,    1,    2,    3,    4,    5, 1234,    7,    8,    9])

In [91]:
arr = np.random.randn(4,4)
arr

array([[ 0.67553155,  0.66893825,  2.29309139, -0.01548371],
       [ 0.12285389,  1.73034759,  1.94848079, -0.55979789],
       [-0.68770448,  1.43890444, -1.33972029,  1.06123217],
       [ 1.04390665, -0.12186478,  0.42959826,  1.38277259]])

In [94]:
np.where(arr > 1,1,arr)

array([[ 0.67553155,  0.66893825,  1.        , -0.01548371],
       [ 0.12285389,  1.        ,  1.        , -0.55979789],
       [-0.68770448,  1.        , -1.33972029,  1.        ],
       [ 1.        , -0.12186478,  0.42959826,  1.        ]])

In [95]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [96]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [98]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)

In [100]:
#求逆
inv(mat)

array([[ 18.81620144,   1.17089317,   4.54214852,  -4.07518694,
        -12.21919184],
       [  1.17089317,   0.42940826,   0.49577991,  -1.19542038,
         -1.41154609],
       [  4.54214852,   0.49577991,   1.5304135 ,  -1.80125218,
         -4.14882943],
       [ -4.07518694,  -1.19542038,  -1.80125218,   6.6390483 ,
          3.80478895],
       [-12.21919184,  -1.41154609,  -4.14882943,   3.80478895,
         14.4056345 ]])

In [110]:
mat.dot(inv(mat)).astype('float16')

array([[ 1.,  0., -0.,  0., -0.],
       [-0.,  1., -0., -0., -0.],
       [-0., -0.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1., -0.],
       [ 0.,  0., -0.,  0.,  1.]], dtype=float16)

# Pandas

In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [7]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [8]:
frame.describe(include='O')

state
count        6
unique       2
top     Nevada
freq         3

In [9]:
frame.describe()

year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

In [10]:
list(frame.columns)

['state', 'year', 'pop']

In [11]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [12]:
frame['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [13]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [14]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
   ....:                       index=['one', 'two', 'three', 'four',
   ....:                              'five', 'six'])

In [15]:
frame2.head()

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [16]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [20]:
frame2.debt = np.arange(6.)

In [21]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [22]:
frame2['eastern'] = frame2.state == 'Ohio'

In [23]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   5.0    False

In [24]:
del frame2['eastern']

In [26]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
....:        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [27]:
frame3.columns.name = 'state'
frame3.index.name = 'year'

In [28]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [29]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [31]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [32]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [33]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [44]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [35]:
new_obj = obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [36]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [38]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
   .....:                     columns=['one', 'two', 'three', 'four'])

In [39]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [45]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [46]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [47]:
obj[[2,3]]

c    2.0
d    3.0
dtype: float64

In [49]:
obj[obj>=2]

c    2.0
d    3.0
dtype: float64

In [51]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
   .....:                     columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [52]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [53]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [57]:
data.iloc[1,[1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [58]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
   .....:                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.511582  0.375858 -0.487681
Ohio   -0.732773 -1.313111 -1.194917
Texas  -0.908372 -1.286757  0.459898
Oregon -0.488917 -0.599107  0.588884

In [59]:
np.abs(frame)

b         d         e
Utah    0.511582  0.375858  0.487681
Ohio    0.732773  1.313111  1.194917
Texas   0.908372  1.286757  0.459898
Oregon  0.488917  0.599107  0.588884

In [60]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.419954
d    1.688969
e    1.783801
dtype: float64

In [61]:
frame.b.value_counts()

-0.488917    1
-0.908372    1
 0.511582    1
-0.732773    1
Name: b, dtype: int64

In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [6]:
string_data[string_data.isna()]

2    NaN
dtype: object

In [7]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [8]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
   ....:                      [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [17]:
df.fillna(0)

0         1         2
0 -0.901134  0.000000  0.000000
1  0.302269  0.000000  0.000000
2 -0.259492  0.000000  2.037120
3 -0.934398  0.000000 -1.597817
4 -1.292712 -0.329432 -0.740928
5 -1.045820  1.971433 -0.701319
6  0.795231 -0.545145 -1.149888

In [18]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.901134  0.500000  0.000000
1  0.302269  0.500000  0.000000
2 -0.259492  0.500000  2.037120
3 -0.934398  0.500000 -1.597817
4 -1.292712 -0.329432 -0.740928
5 -1.045820  1.971433 -0.701319
6  0.795231 -0.545145 -1.149888

In [19]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [20]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
   ....:                      'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [21]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [22]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [23]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
   ....:                               'Pastrami', 'corned beef', 'Bacon',
   ....:                               'pastrami', 'honey ham', 'nova lox'],
   ....:                      'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [24]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
data['animal']  = data['food'].str.lower().map(meat_to_animal)

In [25]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [26]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [27]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [28]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [32]:
cats.codes.tolist()

[0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1]

In [33]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [35]:
data = np.random.randn(20)
pd.cut(data,4,precision = 2)

[(0.86, 1.7], (-1.65, -0.81], (0.025, 0.86], (-0.81, 0.025], (-0.81, 0.025], ..., (0.025, 0.86], (-1.65, -0.81], (-0.81, 0.025], (0.86, 1.7], (-0.81, 0.025]]
Length: 20
Categories (4, interval[float64]): [(-1.65, -0.81] < (-0.81, 0.025] < (0.025, 0.86] < (0.86, 1.7]]

In [36]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)

In [37]:
pd.value_counts(cats)

(0.623, 3.483]       250
(0.00619, 0.623]     250
(-0.708, 0.00619]    250
(-3.319, -0.708]     250
dtype: int64

In [38]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([2, 3, 1, 0, 4])

In [39]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19

In [40]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                    'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [42]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [47]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [51]:
np.random.seed(42)
values = np.random.rand(10)

In [53]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           1           0           0           0
1           0           0           0           0           1
2           0           0           0           1           0
3           0           0           1           0           0
4           1           0           0           0           0
5           1           0           0           0           0
6           1           0           0           0           0
7           0           0           0           0           1
8           0           0           0           1           0
9           0           0           0           1           0

In [54]:
data = pd.Series(np.random.randn(9),
   ...:                  index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
   ...:                         [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -0.469474
   2    0.542560
   3   -0.463418
b  1   -0.465730
   3    0.241962
c  1   -1.913280
   2   -1.724918
d  2   -0.562288
   3   -1.012831
dtype: float64

In [55]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [56]:
data.loc[:,2]

a    0.542560
c   -1.724918
d   -0.562288
dtype: float64

In [57]:
data.unstack()

1         2         3
a -0.469474  0.542560 -0.463418
b -0.465730       NaN  0.241962
c -1.913280 -1.724918       NaN
d       NaN -0.562288 -1.012831

In [58]:
data.unstack().stack()

a  1   -0.469474
   2    0.542560
   3   -0.463418
b  1   -0.465730
   3    0.241962
c  1   -1.913280
   2   -1.724918
d  2   -0.562288
   3   -1.012831
dtype: float64

In [59]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
   ....:                      index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
   ....:                      columns=[['Ohio', 'Ohio', 'Colorado'],
   ....:                               ['Green', 'Red', 'Green']])

In [60]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [61]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
   ....:                       'c': ['one', 'one', 'one', 'two', 'two',
   ....:                             'two', 'two'],
   ....:                       'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [63]:
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [64]:
frame.set_index(['c','d'],drop = False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [65]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [66]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
   ....:                     'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
   ....:                     'data2': range(3)})

In [69]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [70]:
pd.merge(df1,df2, how = 'outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [71]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [72]:
pd.concat([s1,s2,s3], axis = 1)

c:\users\wei\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [78]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
pd.concat([df1,df2])

c:\users\wei\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


a         b         c         d
0  1.538037 -0.035826  1.564644 -2.619745
1  0.821903  0.087047 -0.299007  0.091761
2 -1.987569 -0.219672  0.357113  1.477894
0 -0.501757 -0.518270       NaN -0.808494
1 -0.529760  0.915402       NaN  0.328751

Empty DataFrame
Columns: [a, b, c, d]
Index: []